@Budgify_HostAddress = https://localhost:7068

### GET ALL BUDGETS
GET {{Budgify_HostAddress}}/api/budget
Accepts: application/json

### CREATE A BUDGET
POST {{Budgify_HostAddress}}/api/budget
Content-Type: application/json
{
  "name": "August 1st half"
}

### GET A BUDGET
GET {{Budgify_HostAddress}}/api/budget/fd83b820-c2de-4b10-81bd-d33e6ae23c40
Accepts: application/json

### UPDATE A BUDGET
PUT {{Budgify_HostAddress}}/api/budget/fd83b820-c2de-4b10-81bd-d33e6ae23c40
Content-Type: application/json
{
  "Name": "August First Half"
}

### DELETE A BUDGET
DELETE {{Budgify_HostAddress}}/api/budget/fd83b820-c2de-4b10-81bd-d33e6ae23c40

