@Budgify_HostAddress = https://localhost:7068

### GET ALL BUDGETS
GET {{Budgify_HostAddress}}
Accepts: application/json

### CREATE A BUDGET
POST {{Budgify_HostAddress}}
Content-Type: application/json
{
  "name": "August 1st half"
}

### GET A BUDGET
GET {{Budgify_HostAddress}}/ed7ccafe-4f64-4d8d-804b-c41137cce45c
Accepts: application/json

### UPDATE A BUDGET
PUT {{Budgify_HostAddress}}/0974be10-a0aa-433f-843b-b6a4a457b6fc
Content-Type: application/json
{
  "Name": "August First Half"
}

### DELETE A BUDGET
DELETE {{Budgify_HostAddress}}/ed7ccafe-4f64-4d8d-804b-c41137cce45c

